spring.application.name=cms

spring.datasource.url=jdbc:mysql://localhost:3308/cms
spring.datasource.username=cmsuser
spring.datasource.password=cmspass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=localhost
spring.mail.port=1026

spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

application.frontend.url=http://localhost:8080/api/auth
application.mail.from=noreply@cms.local

application.security.jwt.secret-key=829tP5/uhR/m4YRtGBhgabT1C+5BkkjB0zOWYgzjZpjzqerPmQ7LZwkdIR+ht7AfYt86aQSxAZ1W0kjBaIo/Cw==
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000